### PR TITLE
Amarja SeleniumAssignment2 Q1 to Q 5

### PR DESCRIPTION
**Pull request by AmarjaBTechnocredits**
Hi Ankush & Hi Saket,

Please review Selenium Assignment 2 Q1 to Q 5 by 12-Mar EOD

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Your rowcount size is returning 10 rows because of xpath is //table[@class='table table-striped']//tr.
Xpath = //table[@class='table table-striped']//tbody/tr is returning 9.

List and set variable name needs to be logically as suggested by maulik :)

**Comment by AmarjaBTechnocredits** [comment]
Comments Incorporated

**Comment by AmarjaBTechnocredits** [comment]
Hi Rahul please review the code and provide your comments and approval for same

**Review by RahulVarma23 — APPROVED** [review]
you have added implicit wait of 1 second.If script is unable to locate element in a second(or slow internet) then it will throw NoSuchElementException. So I will suggest to increase wait by few seconds.Rest of the code looks fantastic.

**Comment by AmarjaBTechnocredits** [comment]
Received Approval .Krishna please review

**Review by ghost — APPROVED** [review]

**Review by KrishnaKTechnocredits — APPROVED** [review]
You can incorporate below changes from your next PR;
1) Give meaningful HashSet or map or any variable name.
2) Before every set of code, please add small comments about what are you going to achieve in for loop or condition. (Like a test step)
So on the base of your comments, anyone should understand what are you going to perform in that code. 
Logic and code writing is good. 
Rest of the code looks good to me. Keep it up :

**Pull request merged**
